# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dc5e62de239a1f0da0b86f497b8929fc61e5d562b6c2bed9843cc0e3195131e4283735fe1026acb059929ae742738a9f5150c5b07af30e43714c33a9d5e7c98

test:
  secret_key_base: c1e14e03104884c6d6fa10bf4509e574fd71609d0d0ce2900c6894bdc18f157a60496da2d81f240cfb31c1bc6eea70d621733804ca7d02779296a8d106c9576e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
